# SPDX-License-Identifier: MIT
"""Firepit SDK — auto-generated by HACS Integration Engine."""
from .client import (
    LOCAL_NAME,
    SERVICE_UUIDS,
    FirepitClient,
    FirepitConnectionError,
    matches,
)

__all__ = [
    "LOCAL_NAME",
    "SERVICE_UUIDS",
    "FirepitClient",
    "FirepitConnectionError",
    "matches",
]
