# SPDX-License-Identifier: MIT
"""P2-1d — GraphQL operations generated by Apollo Kotlin.

Apollo generates one class per operation with OPERATION_NAME and the full
OPERATION_DOCUMENT, plus typed nested data classes (``Data`` → ``Metrics`` →
``Cpu { double percentTotal }``). From those:

  mutation      → TO_DEVICE command     (variables → typed request fields)
  query         → TO_DEVICE query       (typed leaf paths → response fields)
  subscription  → FROM_DEVICE event

The endpoint path (usually ``/graphql``) and an API-key header are read from
first-party code, including R8-obfuscated classes outside the package folder.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

from ..ir.models import (
    AuthScheme,
    AuthType,
    Direction,
    Endpoint,
    FieldDef,
    FieldKind,
    TransportType,
)
from . import confidence
from .app_sources import app_source_files, is_third_party

_LOGGER = logging.getLogger(__name__)

_DOCUMENT = re.compile(r'return\s+"((?:query|mutation|subscription)\s+(\w+)[^"]*)"')
_HEADER = re.compile(r"^(query|mutation|subscription)\s+(\w+)\s*(?:\(([^)]*)\))?")
_VARIABLE = re.compile(r"\$(\w+)\s*:\s*(\[?\w+!?\]?)(!?)")
_NESTED_CLASS = re.compile(r"public static final class (\w+)\b[^{]*\{")
_FIELD = re.compile(r"^\s+private final ([\w.<>]+) (\w+);", re.MULTILINE)
_API_KEY_HEADER = re.compile(r'"((?:x-)?api[-_]?key|x-auth-token)"', re.IGNORECASE)
_GRAPHQL_PATH = re.compile(r'"(/[\w/-]*graphql)"')

_SCALARS = {
    "Int": FieldKind.INTEGER,
    "Float": FieldKind.NUMBER,
    "Boolean": FieldKind.BOOLEAN,
    "String": FieldKind.STRING,
    "ID": FieldKind.STRING,
}
_JAVA_KINDS = {
    "int": FieldKind.INTEGER,
    "Integer": FieldKind.INTEGER,
    "long": FieldKind.INTEGER,
    "Long": FieldKind.INTEGER,
    "double": FieldKind.NUMBER,
    "Double": FieldKind.NUMBER,
    "float": FieldKind.NUMBER,
    "Float": FieldKind.NUMBER,
    "boolean": FieldKind.BOOLEAN,
    "Boolean": FieldKind.BOOLEAN,
    "String": FieldKind.STRING,
    "Object": FieldKind.STRING,
}
_MAX_DEPTH = 5


@dataclass
class GraphQLScan:
    commands: list[Endpoint]
    events: list[Endpoint]
    path: str
    auth: AuthScheme
    poll_queries: list[str]
    state: list[FieldDef]


def scan(apk_out_dir: Path, app_package: str) -> GraphQLScan | None:
    sources = apk_out_dir / "sources"
    if not sources.exists():
        return None
    commands: list[Endpoint] = []
    events: list[Endpoint] = []
    for f in app_source_files(sources, app_package):
        src = f.read_text(errors="replace")
        if "OPERATION_DOCUMENT" not in src:
            continue
        doc = _DOCUMENT.search(src)
        if doc is None:
            continue
        ep = _operation(doc.group(1).encode().decode("unicode_escape"), src, f.stem)
        (events if ep.direction == Direction.FROM_DEVICE else commands).append(ep)
    if not commands and not events:
        return None

    first_party = _first_party_texts(sources)
    path = next((m for src in first_party for m in _GRAPHQL_PATH.findall(src)), "/graphql")
    header = next((m for src in first_party for m in _API_KEY_HEADER.findall(src)), None)
    auth = (
        AuthScheme(
            type=AuthType.API_KEY,
            fields=[FieldDef(name=header, serialized_name=header, kind=FieldKind.STRING)],
            description=f"API key sent in the '{header}' header",
        )
        if header
        else AuthScheme(type=AuthType.NONE)
    )
    polls = _poll_queries(commands)
    _LOGGER.info(
        "graphql_scanner: %d operations at %s (auth=%s, poll=%s)",
        len(commands) + len(events),
        path,
        auth.type.value,
        [p.cmd for p in polls],
    )
    return GraphQLScan(
        commands=commands,
        events=events,
        path=path,
        auth=auth,
        poll_queries=[p.cmd for p in polls],
        state=[f for p in polls for f in p.response_fields if f.kind != FieldKind.ARRAY],
    )


def _operation(document: str, src: str, cls: str) -> Endpoint:
    header = _HEADER.match(document)
    assert header is not None
    kind, name, variables = header.groups()
    request = [
        FieldDef(
            name=var,
            serialized_name=var,
            kind=FieldKind.ARRAY
            if gql_type.startswith("[")
            else _SCALARS.get(gql_type.strip("!"), FieldKind.STRING),
            required=gql_type.endswith("!") or bool(bang),
        )
        for var, gql_type, bang in _VARIABLE.findall(variables or "")
    ]
    return Endpoint(
        cmd=f"{kind.upper()} {name}",
        transport=TransportType.GRAPHQL,
        direction=Direction.FROM_DEVICE if kind == "subscription" else Direction.TO_DEVICE,
        awaits_response=kind != "subscription",
        request_fields=request,
        response_fields=_leaf_fields(src, document) if kind == "query" else [],
        source_class=cls,
        document=document,
        confidence=confidence.score(confidence.NAME_ANNOTATION, confidence.FIELDS_TYPED),
    )


def _leaf_fields(src: str, document: str) -> list[FieldDef]:
    """Typed scalar leaves reachable from the nested ``Data`` class, as dotted paths."""
    words = set(re.findall(r"\w+", document))
    classes: dict[str, list[tuple[str, str]]] = {}
    for m in _NESTED_CLASS.finditer(src):
        body_end = src.find("\n    }", m.end())
        classes[m.group(1)] = [
            (java_type, _wire_name(field, words))
            for java_type, field in _FIELD.findall(src[m.end() : body_end])
        ]

    leaves: list[FieldDef] = []

    def walk(cls: str, prefix: str, depth: int) -> None:
        for java_type, field in classes.get(cls, []):
            path = f"{prefix}{field}"
            if java_type.startswith("List<"):
                leaves.append(
                    FieldDef(name=_identifier(path), serialized_name=path, kind=FieldKind.ARRAY)
                )
            elif java_type in classes and depth < _MAX_DEPTH:
                walk(java_type, path + ".", depth + 1)
            else:
                kind = _JAVA_KINDS.get(java_type, FieldKind.ENUM)
                nullable = java_type[:1].isupper() and java_type != "String"
                leaves.append(
                    FieldDef(
                        name=_identifier(path), serialized_name=path, kind=kind, nullable=nullable
                    )
                )

    walk("Data", "", 0)
    return leaves


_MAX_POLL_QUERIES = 5


def _identifier(path: str) -> str:
    """metrics.cpu.percentTotal → metrics_cpu_percent_total (the wire path stays dotted)."""
    snake = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", path.replace(".", "_"))
    return snake.lower()


def _wire_name(field: str, document_words: set[str]) -> str:
    """JADX renames clashing fields (os → f5014os); the document has the real name."""
    renamed = re.fullmatch(r"f\d+([a-z]\w*)", field)
    if renamed and renamed.group(1) in document_words:
        return renamed.group(1)
    return field


def _poll_queries(commands: list[Endpoint]) -> list[Endpoint]:
    """Queries to poll for state: no required variables and some scalar leaves.

    Their leaves are rooted under each query's own top-level field (info.*,
    metrics.*, array.*), so fetching several per refresh can't collide.
    """
    scored = []
    for c in commands:
        if not c.cmd.startswith("QUERY ") or any(f.required for f in c.request_fields):
            continue
        scalars = sum(f.kind != FieldKind.ARRAY for f in c.response_fields)
        if scalars:
            scored.append((scalars, c.cmd, c))
    return [c for _, _, c in sorted(scored, key=lambda s: (-s[0], s[1]))[:_MAX_POLL_QUERIES]]


def _first_party_texts(sources: Path) -> list[str]:
    """All non-library sources, including obfuscated packages outside the app folder."""
    texts = []
    for f in sources.rglob("*.java"):
        dotted = ".".join(f.relative_to(sources).with_suffix("").parts)
        if not is_third_party(dotted):
            texts.append(f.read_text(errors="replace"))
    return texts
